### ISSUE TITLE
Why ion-nav don't work with Blazor ?

### ISSUE THREAD

**Issue by aboudoux** [Kukks/Blazor.Ionic#1]
Hello, 
Good job for this project.

I'm trying to implement a `ion-nav` on my app like this : https://ionicframework.com/docs/api/nav
but it look that a `<ion-item button />` dont work properly.

You haven't made this component in your library. Is it about a known limitation ?

**Comment by Kukks** [comment]
There is an `IonItem` component. What is the issue?

**Comment by Kukks** [comment]
If you are a referring to Ion nav, it is not supported by this llibrary and should also be avoided in a blazor environment.  I have done an example of a stack navigation system using blazor and ionic in this PR of a project using this lib : https://github.com/chaincase-app/chaincase/pull/100
