### ISSUE TITLE
bind remaining ion-element to IonElement

### ISSUE THREAD

**Issue by DanGould** [Kukks/Blazor.Ionic#5]
This would make the lib feel more complete. It would be much easier for newcomers to use without having to think "does this have the potential to be 2-way bound?" Then it's behavior is almost identical to the react library and thus familiar for web devs.

Could this be done in one component that wraps or would a new wrapper need to be written for all remaining components?

**Comment by Kukks** [comment]
done in https://github.com/Kukks/Blazor.Ionic/commit/4a9694d9f5cf17e37fce35cdf25335a36eb7e1c3

**Comment by DanGould** [comment]
my hero
