### ISSUE TITLE
Problem responsive on sm size

### ISSUE THREAD

**Issue by Pant76** [Kukks/Blazor.Ionic#8]
![Capture](https://user-images.githubusercontent.com/3235695/117546045-b95d1e00-b028-11eb-8136-05683c7fa12e.JPG)

I can't solve this!
Also in your demo at:
https://kukks.github.io/Blazor.Ionic/demo

**Comment by Pant76** [comment]
i solved with this:

<style>
    .mainBlock {
        display: block !important;
    }
</style>
<IonSplitPane when="sm" content-id="main-content" class="mainBlock">

**Comment by Kukks** [comment]
Sorry for the long delay. I added a patch for this inside IonSplitPane, which is on by default. You can turn it off using `ApplyStyleFix="false"`
